language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install -U pip
  - pip install tox-travis

before_script:
  - pip install -r requirements.txt
  - cd doudizhu

script:
  - coverage run tests

after_success:
  - coveralls
