version: "3"

services:
  doudizhu:
    image: doudizhu:latest
    container_name: doudizhu
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./ddz.log:ddz.log
    restart: always
    network_mode: host
